"""estrutura inicial limpa

Revision ID: d088e1793d29
Revises: 779d3a03910a
Create Date: 2025-05-31 14:22:13.005848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd088e1793d29'
down_revision: Union[str, None] = '779d3a03910a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tipo_servico'), table_name='servico')
    op.drop_table('servico')
    op.drop_table('mensagem')
    op.drop_index(op.f('id_usuario'), table_name='login')
    op.drop_table('login')
    op.drop_table('solicitacao')
    op.drop_index(op.f('email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('cnpj'), table_name='pessoa_juridica')
    op.drop_table('pessoa_juridica')
    op.drop_table('fale_conosco')
    op.drop_index(op.f('idx_servico_foto_servico'), table_name='servico_foto')
    op.drop_table('servico_foto')
    op.drop_index(op.f('idx_nome_produto'), table_name='produto')
    op.drop_table('produto')
    op.drop_index(op.f('idx_produto_foto_produto'), table_name='produto_foto')
    op.drop_table('produto_foto')
    op.drop_index(op.f('cnpj'), table_name='loja')
    op.drop_index(op.f('id_usuario'), table_name='loja')
    op.drop_table('loja')
    op.drop_index(op.f('id_usuario'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('idx_fazenda_foto_fazenda'), table_name='fazenda_foto')
    op.drop_table('fazenda_foto')
    op.drop_index(op.f('id_usuario'), table_name='prestador')
    op.drop_table('prestador')
    op.drop_index(op.f('idx_nome_fazenda'), table_name='fazenda')
    op.drop_table('fazenda')
    op.drop_index(op.f('cpf'), table_name='pessoa_fisica')
    op.drop_table('pessoa_fisica')
    op.drop_index(op.f('nome'), table_name='tipo_usuario')
    op.drop_table('tipo_usuario')
    op.drop_table('endereco')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rua', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('numero', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cidade', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.CHAR(length=2), nullable=False),
    sa.Column('cep', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('complemento', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipo_usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nome'), 'tipo_usuario', ['nome'], unique=True)
    op.create_table('pessoa_fisica',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('rg', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_nascimento', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('pessoa_fisica_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('cpf'), 'pessoa_fisica', ['cpf'], unique=True)
    op.create_table('fazenda',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id_endereco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('area_total', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], name='fazenda_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], name='fazenda_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_nome_fazenda'), 'fazenda', ['nome'], unique=False)
    op.create_table('prestador',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('localizacao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avaliacao_media', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_registro', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('prestador_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_usuario'), 'prestador', ['id_usuario'], unique=True)
    op.create_table('fazenda_foto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_fazenda', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_foto', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_fazenda'], ['fazenda.id'], name=op.f('fazenda_foto_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_fazenda_foto_fazenda'), 'fazenda_foto', ['id_fazenda'], unique=False)
    op.create_table('cliente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_endereco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_registro', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], name='cliente_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='cliente_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_usuario'), 'cliente', ['id_usuario'], unique=True)
    op.create_table('loja',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('razao_social', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id_endereco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], name='loja_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='loja_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_usuario'), 'loja', ['id_usuario'], unique=True)
    op.create_index(op.f('cnpj'), 'loja', ['cnpj'], unique=True)
    op.create_table('produto_foto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_produto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_foto', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], name=op.f('produto_foto_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_produto_foto_produto'), 'produto_foto', ['id_produto'], unique=False)
    op.create_table('produto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('preco', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('desconto', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('quantidade_estoque', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('id_loja', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], name=op.f('produto_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_nome_produto'), 'produto', ['nome'], unique=False)
    op.create_table('servico_foto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_foto', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_servico'], ['servico.id'], name=op.f('servico_foto_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_servico_foto_servico'), 'servico_foto', ['id_servico'], unique=False)
    op.create_table('fale_conosco',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assunto', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mensagem', mysql.TEXT(), nullable=False),
    sa.Column('data_envio', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('fale_conosco_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pessoa_juridica',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('razao_social', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('cnae', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('inscricao_estadual', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('pessoa_juridica_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('cnpj'), 'pessoa_juridica', ['cnpj'], unique=True)
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tipo_usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endereco_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('ATIVO', 'INATIVO', 'PENDENTE'), server_default=sa.text("'ATIVO'"), nullable=True),
    sa.Column('foto_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id_endereco', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id'], name='usuario_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], name='usuario_ibfk_3', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_usuario_id'], ['tipo_usuario.id'], name='usuario_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'usuario', ['email'], unique=True)
    op.create_table('solicitacao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_servico', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'pendente'"), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], name=op.f('solicitacao_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servico'], ['servico.id'], name=op.f('solicitacao_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('login',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('senha_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ultimo_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('ativo', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('login_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_usuario'), 'login', ['id_usuario'], unique=True)
    op.create_table('mensagem',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_remetente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_destinatario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conteudo', mysql.TEXT(), nullable=False),
    sa.Column('data_envio', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_destinatario'], ['usuario.id'], name=op.f('mensagem_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_remetente'], ['usuario.id'], name=op.f('mensagem_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('servico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=False),
    sa.Column('preco', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('localizacao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_atualizacao', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('servico_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_tipo_servico'), 'servico', ['tipo'], unique=False)
    # ### end Alembic commands ###
